security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        pdo_mysql:
            entity:
                class: App\Entity\FDUser
                property: login

    firewalls:
        main:
            pattern:    ^/
            http_basic: ~
            provider: pdo_mysql
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                default_target_path: map
            logout:
                path:   /logout
                target: /
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

            # activate different ways to authenticate

            # http_basic: true
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: true
            # https://symfony.com/doc/current/security/form_login_setup.html

    access_control:
        - { path: /_wdt/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }  ### These 2 lines needed
        - { path: /_profiler/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }

    encoders:
        App\Entity\FDUser:
            id: App\Security\PhpassEncoder